---
version: "3"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: ["azurite-blob", "--blobHost", "0.0.0.0", "--oauth", "basic" ,"--cert", "/workspace/cert.pem", "--key", "/workspace/key.pem"]
    ports:
      - 10000:10000
    volumes:
      - ./certs:/workspace
  mockazuread:
    image: simondrake/mockazuread:latest
    container_name: mockazuread
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - CONNECTION_TENANT_ID=mytenantid
      - CONNECTION_ENDPOINT=https://127.0.0.1:8080
    volumes:
      - ./certs:/certs
