---
version: "3"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: ["azurite-blob", "--blobHost", "0.0.0.0", "--oauth", "basic" ,"--cert", "/workspace/cert.pem", "--key", "/workspace/key.pem"]
    ports:
      - 10000:10000
    volumes:
      - /tmp/mockazurecerts:/workspace
  mockazuread:
    image: simondrake/mockazuread:latest
    container_name: mockazuread
    ports:
      - 8080:8080
    environment:
      - MOCKAZURE_SERVER_PORT=8080
      - MOCKAZURE_CONNECTION_TENANTID=mytenantid
      - MOCKAZURE_CONNECTION_ENDPOINT=https://127.0.0.1:8080
      - MOCKAZURE_AUTHENTICATION_SIGNINGKEY=wibblewobble
      - MOCKAZURE_CONNECTION_CERTDIRECTORY=/certs
      - MOCKAZURE_CONNECTION_CERTNAME=cert.pem
      - MOCKAZURE_CONNECTION_KEYNAME=key.pem
    volumes:
      - /tmp/mockazurecerts:/certs
