apiVersion: v1
kind: Service
metadata:
  name: mockazuread
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
      nodePort: 30750
  selector:
    name: mockazuread
  type: NodePort
